import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx"),
  route("appearance", "./routes/appearance.ts"),
  route("catalog-notifications", "./routes/catalog-notifications.ts"),
  route("key-ceremony", "./routes/key-ceremony.ts"),
  route("settings/security", "./routes/settings.security.tsx"),
  route("settings/api-keys", "./routes/settings.api-keys.tsx"),
  route("settings/api-keys/copy", "./routes/settings.api-keys.copy.ts"),
  route("api/v1/daily-log", "./routes/api.v1.daily-log.ts"),
  route("food-events", "./food-event/routes/web.ts"),
  route("api/v1/food-events", "./food-event/routes/api.v1.food-events.ts"),
  route("api/v1/catalog", "./catalog/routes/api.v1.catalog.ts"),
  route("water-events", "./water-event/routes/web.ts"),
  route("api/v1/water-events", "./water-event/routes/api.v1.water-events.ts"),
  route("mcp", "./routes/mcp.ts"),
  route("login", "./routes/login.tsx"),
  route("logout", "./routes/logout.tsx"),
  route("register", "./routes/register.tsx"),
  route("setup", "./routes/setup.tsx"),
  route("settings/goals", "./daily-goal/routes/settings.goals.tsx"),
  route("settings/catalogs", "./routes/settings.catalogs.tsx"),
  route("settings/users", "./routes/settings.users.tsx"),
  route("account/password", "./routes/account.password.tsx"),
  route("health/live", "./routes/health.live.ts"),
  route("health/ready", "./routes/health.ready.ts"),
  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
