import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx"),
  route("appearance", "./routes/appearance.ts"),
  route("catalog-notifications", "./routes/catalog-notifications.ts"),
  route("photo-analysis", "./routes/photo-analysis.ts"),
  route("key-ceremony", "./routes/key-ceremony.ts"),
  route("settings/security", "./routes/settings.security.tsx"),
  route("settings/api-keys", "./routes/settings.api-keys.tsx"),
  route("settings/api-keys/copy", "./routes/settings.api-keys.copy.ts"),
  route("settings/oauth-clients", "./routes/settings.oauth-clients.tsx"),
  route("oauth/authorize", "./routes/oauth.authorize.tsx"),
  route("oauth/token", "./routes/oauth.token.ts"),
  route(".well-known/oauth-authorization-server", "./routes/oauth.metadata.ts"),
  route("api/v1/daily-log", "./routes/api.v1.daily-log.ts"),
  route("login", "./routes/login.tsx"),
  route("logout", "./routes/logout.tsx"),
  route("register", "./routes/register.tsx"),
  route("setup", "./routes/setup.tsx"),
  route("settings/goals", "./routes/settings.goals.tsx"),
  route("settings/catalogs", "./routes/settings.catalogs.tsx"),
  route("settings/ai", "./routes/settings.ai.tsx"),
  route("settings/users", "./routes/settings.users.tsx"),
  route("account/password", "./routes/account.password.tsx"),
  route("health/live", "./routes/health.live.ts"),
  route("health/ready", "./routes/health.ready.ts"),
  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
